Add ability to use custom  kubeconfig inside tests

diff --git a/docker-run-tests b/docker-run-tests
--- a/docker-run-tests
+++ b/docker-run-tests
@@ -6,16 +6,22 @@ if [[ $KIND_KEEP_ORIGINAL_CLUSTER == 0 ]]; then
 
     echo "-> creating kind cluster..."
     kind create cluster
+
+    exit_code=$?
+    if [[ $exit_code != 0 ]]; then
+        echo "<- failed to create kind cluster"
+        exit $exit_code
+    fi
 fi
 
-exit_code=$?
-if [[ $exit_code != 0 ]]; then
-    echo "<- failed to create kind cluster"
-    exit $exit_code
+if [[ -z "$KUBECONFIG" ]]; then
+    # export kube config
+    export KUBECONFIG="$(kind get kubeconfig-path)"
 fi
 
-# export kube config
-export KUBECONFIG="$(kind get kubeconfig-path)"
+if [[ -n "$KIND_COPY_KUBECONFIG_TO" ]]; then
+    cp $KUBECONFIG $KIND_COPY_KUBECONFIG_TO
+fi
 
 echo "-> init helm..."
 kubectl create serviceaccount --namespace kube-system tiller
